spring:
  config:
    import: classpath:application-flowfoundry-platform.yml
  application:
    name: flowfoundry

flowfoundry:
  security:
    dev-namespace: default
    bootstrap-admin-key: ${FLOWFOUNDRY_BOOTSTRAP_ADMIN_KEY:local-admin-key}
    api-keys:
      - client-id: platform-admin
        key: ${FLOWFOUNDRY_ADMIN_API_KEY:local-admin-key}
        admin: true
        namespaces: []
