spring:
  config:
    import:
      - classpath:application-flowfoundry-platform.yml
      - classpath:application-flowfoundry-worker.yml
  application:
    name: ai-collection-strategy

temporal:
  host: ${TEMPORAL_HOST:127.0.0.1:7233}

platform:
  activity-registry:
    path: ${ACTIVITY_REGISTRY_PATH:classpath:activities-registry.yaml}

flowfoundry:
  activity-registry:
    path: ${ACTIVITY_REGISTRY_PATH:classpath:activities-registry.yaml}
